import { IQuestion } from '../interfeces/question';

export const questions: IQuestion[] = [
  {
    section: '0 - Necesidad de Aceptación por parte de los demás',
    question: 'Es importante para mi que los demás me aprueben.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '0 - Necesidad de Aceptación por parte de los demás',
    question: 'Me gusta el respeto de los otros pero no necesito 6 tenerlo.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '0 - Necesidad de Aceptación por parte de los demás',
    question: 'Quiero gustar a todo el mundo.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '0 - Necesidad de Aceptación por parte de los demás',
    question:
      'Puedo gustarme a mi mismo incluso cuando no les agrado a otras personas.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '0 - Necesidad de Aceptación por parte de los demás',
    question: 'Si no gusto a otras personas es su problema no el mío.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '0 - Necesidad de Aceptación por parte de los demás',
    question:
      'Aunque me gusta la aprobación. no es una autentica necesidad para mi.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '0 - Necesidad de Aceptación por parte de los demás',
    question: 'Es molesto pero no insoportable que te critiquen.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '1 - Altas Autoexpectativas',
    question: 'Odio fallar en cualquier cosa.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '1 - Altas Autoexpectativas',
    question:
      'Me gusta tener éxito en cualquier cosa pero no siento que lo tenga que lograr.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '1 - Altas Autoexpectativas',
    question:
      'Para mí es extremadamente importante tener éxito en todo lo que hago.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '1 - Altas Autoexpectativas',
    question: 'No me importa realizar cosas que no puedo hacer bien.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '1 - Altas Autoexpectativas',
    question:
      'Se puede disfrutar de las actividades por si mismas sin importar lo bueno que sea en ellas.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '2 - Culpabilización',
    question: 'Las personas que actúan mal merecen lo que les ocurre.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '2 - Culpabilización',
    question: 'Demasiadas malas personas escapan al castigo que merecen.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '2 - Culpabilización',
    question: 'Aquellos que actúan mal deben ser castigados.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '2 - Culpabilización',
    question: 'La inmoralidad debería castigarse intensamente.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '2 - Culpabilización',
    question: 'Todo el mundo es básicamente bueno.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '2 - Culpabilización',
    question: 'Nadie es malvado. incluso cuando sus actos lo sean.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '3 - Intolerancia a la frustración',
    question: 'Es mejor 3 aceptar las cosas como son. incluso si no me gustar.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '3 - Intolerancia a la frustración',
    question: 'Las cosas deberían ser diferentes de cómo son.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '3 - Intolerancia a la frustración',
    question: 'Es terrible pasar por situaciones que no me gustan.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '3 - Intolerancia a la frustración',
    question: 'Es difícil para mí realizar tareas desagradables.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '3 - Intolerancia a la frustración',
    question: 'Creo que puedo soportar los errores de los demás.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '3 - Intolerancia a la frustración',
    question: 'Una vida de facilidades rara vez es recompensante.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '4 - Preocupación y ansiedad',
    question:
      'No hay motivo para temer peligros inesperados o sucesos futuros.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '4 - Preocupación y ansiedad',
    question:
      'Si no puedo evitar que Ocurra algo, es mejor no preocuparse por ello.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '4 - Preocupación y ansiedad',
    question: 'No puedo soportar correr riesgos.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '4 - Preocupación y ansiedad',
    question:
      'Es mejor no pensar en cosas tales como la muerte o grandes desastres.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '4 - Preocupación y ansiedad',
    question:
      'Es conveniente planificar lo que haría en diferentes situaciones peligrosas.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '5 - Irresponsabilidad Emocional',
    question:
      'Si una persona quiere, puede ser feliz casi bajo cualquier circunstancia.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '5 - Irresponsabilidad Emocional',
    question:
      'Las personas no se ven perturbadas por las situaciones sino por la forma en que las ven.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '5 - Irresponsabilidad Emocional',
    question: 'Yo soy la causa de mis propios estados de animo.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '5 - Irresponsabilidad Emocional',
    question:
      'Normalmente las personas que son desdichadas se han hecho a sí mismas de esa manera.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '5 - Irresponsabilidad Emocional',
    question:
      'Una persona no permanecerá mucho tiempo enfadada o triste a menos que se mantenga a si misma de esa manera.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '5 - Irresponsabilidad Emocional',
    question:
      'Nada es insoportable en si mismo, solo en la forma en que tú lo interpretas.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '5 - Irresponsabilidad Emocional',
    question: 'La persona hace su propio infierno dentro de si mismo.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '6 - Evitación de Problemas',
    question: 'Es mejor posponer las decisiones importantes.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '6 - Evitación de Problemas',
    question: 'Es preferible tomar las decisiones tan pronto como se pueda.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '6 - Evitación de Problemas',
    question: 'Es mejor evitar las cosas que no puedo hacer bien.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '7 - Dependencia',
    question:
      'Todo el mundo necesita alguien de quien depender para ayuda y consejo.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '7 - Dependencia',
    question:
      'Considero adecuado resolver mis propios asuntos sin ayuda de nadie.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '7 - Dependencia',
    question: 'Encuentro fäc1l aceptar consejos.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '7 - Dependencia',
    question:
      'Soy el único que realmente puede entender y afrontar mis problemas.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '7 - Dependencia',
    question: 'Creo que no tengo que depender de otros.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '7 - Dependencia',
    question:
      'He aprendido a no esperar que otros se preocupen acerca de mi bienestar.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '8 - Indefensíon',
    question: 'Siempre nos acompañaran los mismos problemas.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '8 - Indefensíon',
    question: 'Es casi imposible superar las influencias del pasado.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '8 - Indefensíon',
    question:
      'Por el hecho de que en una ocasión algo afecte de forma importante a tu vida, no significa que tenga que ser necesariamente asi en el futuro.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '8 - Indefensíon',
    question:
      'Rara vez pienso que experiencias del pasado me estén afectando ahora.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '8 - Indefensíon',
    question: 'Somos esclavos de nuestras propias historias personales.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '8 - Indefensíon',
    question: 'Una vez que algo afecta a tu vida siempre lo hará.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '8 - Indefensíon',
    question: 'La gente nunca cambia básicamente.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '9 - Perfeccionismo',
    question: 'Existe una forma correcta de hacer cada cosa.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '9 - Perfeccionismo',
    question: 'No hay una solución perfecta para las cosas.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '9 - Perfeccionismo',
    question:
      'Rara vez hay una forma fácil de resolver las dificultades de la vida.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
  {
    section: '9 - Perfeccionismo',
    question: 'Todo problema tiene una solución correcta.',
    option1: 1,
    option2: 2,
    option3: 3,
    option4: 4,
    option5: 5,
    option6: 6,
  },
  {
    section: '9 - Perfeccionismo',
    question: 'Rara vez hay una solución ideal para las cosas.',
    option1: 6,
    option2: 5,
    option3: 4,
    option4: 3,
    option5: 2,
    option6: 1,
  },
];
